SECRET_KEY='TEST_PUPPIES'
SQLALCHEMY_DATABASE_URI='mysql://travis@localhost/user_authentication'
SQLALCHEMY_TRACK_MODIFICATIONS='FALSE'
SESSION_TYPE='SESSION_SQLALCHEMY'
DEBUG=True
CSRF_ENABLED=True
CSRF_SESSION_KEY="Doggos"
